### PR TITLE
Refine and update README

### PR DESCRIPTION
**Pull request by dexX7**

### CODE REVIEW

**Comment by m21** [comment]
Thanks Dexx.
@zathras-crypto @faizkhan00 how does the language look like, comments please?
(One note: we are going towards renaming Metadex as Dex Phase 2).
(I am used to Metadex personally heh).

**Comment by dexX7** [comment]
Yeah, metadex sounds nice. On the other hand, maybe the whole DEx metaDex or whatever should be replaced by "distributed token exchange" or so. Not sure, if those words are understood by someone who reads it the first time.

Edit: also: Master Core or Mastercore?

**Comment by m21** [comment]
Please see here Dexx: http://blog.mastercoin.org/2014/10/31/the-great-transition/ for your last question. :)

**Comment by dexX7** [comment]
Not relevant at this point. Currently it's still Master Core and based on Bitcoin Core 0.9.3. (Omni _ Core is used, so I assume it's Master _ Core.. :)

**Comment by ghost** [comment]
Supported

**Pull request merged**
