### PR TITLE
Format: calculateFundraiser

### PR DESCRIPTION
**Pull request by dexX7**
Mostly removes depreciated comments, no functional change.

### CODE REVIEW

**Comment by m21** [comment]
TBD after the tag

**Comment by m21** [comment]
After spending considerable time on this, and still not being 100% comfortable, I am now against accepting "non-functional changes" of such magnitude, 100+ LOC in consensus-critical code (this is the Exodus fundraiser!).
Comment cleanup is a valid effort, optionally limited to a few lines.

**Comment by whitj00** [comment]
NACK, no real value.  Needs valid reason for commit when dealing with such code

**Comment by dexX7** [comment]
Partially addressed by https://github.com/OmniLayer/omnicore/pull/17.

**Pull request closed without merging**
