### PR TITLE
0.0.9 to 0.0.9.1

### PR DESCRIPTION
**Pull request by zathras-crypto**
This PR serves to bring the main repo up to version 0.0.9.1 ready for tag & building bins.

@m21 95% of these changes are UI fixes that have gone in following testing with DexX and a couple of minor fixes that don't affect consensus.  I'm going to see what I can drum up in terms of changelog/release notes.

### CODE REVIEW

**Comment by dexX7** [comment]
One moment please. I think it needs a very small adjustment related to the version. Will update within 15 minutes.

Edit: the issue is related to:

``` c++
#ifdef HAVE_BUILD_INFO
#    include "build.h"
#endif
```

... which caused a build error:

```
  CXX    mastercore_version.o
mastercore_version.cpp:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]
mastercore_version.cpp:9:23: fatal error: build.h: No such file or directory
compilation terminated.
make[3]: *** [mastercore_version.o] Error 1
```

A fix is to edit https://github.com/zathras-crypto/mastercore/blob/0.0.9.1-Z/src/Makefile.am#L98:

```
obj/build.h: FORCE
    @$(MKDIR_P) $(abs_top_builddir)/src/obj
    @$(top_srcdir)/share/genbuild.sh $(abs_top_builddir)/src/obj/build.h \
      $(abs_top_srcdir)
version.o: obj/build.h
mastercore_version.o: obj/build.h
```

... which seems to work, but the full build isn't finished yet.

Edit 2:
As alternative:

``` c++
#ifdef HAVE_BUILD_INFO
#    include "build.h"
#endif
```

... could be removed, in the hope that `COMMIT_ID` is already defined at this point.

**Comment by zathras-crypto** [comment]
> One moment please. I think it needs a very small adjustment related to the version. Will update within 15 minutes.

Let me guess, you want to change:
`"mastercoreversion" : "0.0.9.1-dev",`
to
`"omnicoreversion" : "0.0.9.1-dev",`
If so I thought of that too but I hate changing attribute names :(

**Comment by dexX7** [comment]
Nope, see the edit.

**Comment by zathras-crypto** [comment]
Right, where are you seeing this build error?  GItian? (I can build fine?)

**Comment by dexX7** [comment]
Yes, but I'm not 100 % sure why it's happening there. I _think_ it's because it's a fresh build, and building when there was a successful earlier build might be unaffected, because build.h was already generated earlier.

**Comment by zathras-crypto** [comment]
OK, about time I cranked up the old Gitian VM :) (usually I build my windows bins with mingw I found it much quicker).  Will report back soon.

**Comment by zathras-crypto** [comment]
Are you building from my branch?  What URL & COMMIT variables are you using?

**Comment by dexX7** [comment]
At this point there is no straight forward way to go the full Gitian build route and I was going to update the tutorial.

It comes down to:
https://gist.github.com/dexX7/b46f0fea46b9ea881142
But with inputs from [mscore-0.0.9/doc/release-process.md#perform-gitian-builds](https://github.com/mastercoin-MSC/mastercore/blob/mscore-0.0.9/doc/release-process.md#perform-gitian-builds)
And cherry-picking [419045f8a022b9dfd482cd3245331fbe34aa6a24](https://github.com/dexX7/bitcoin/commit/419045f8a022b9dfd482cd3245331fbe34aa6a24)

And then using the commit id of the last commit.

**Comment by dexX7** [comment]
> I think it's because it's a fresh build, ...

Confirmed, this is indeed the case. Unrelated to Gitian.

**Comment by dexX7** [comment]
Either one of the above mentioned solutions works. Not 100 % sure, if the second route shows the commit id. (This build is still ongoing)

**Comment by zathras-crypto** [comment]
EDIT: nonsense removed lol... so making mastercore_version.o depend on build.h right if that works seems straight forward (also please define 'fresh build', I can't replicate that error even after a `make clean`)

**Comment by dexX7** [comment]
@zathras-crypto: yes, this seems to be the case. And otherwise no commit id appears to be available.

**Comment by zathras-crypto** [comment]
Confirm issue
image
 & proposed fix resolves - merging https://github.com/zathras-crypto/mastercore/pull/57 first before merging #293

**Comment by zathras-crypto** [comment]
OK, discussed with @m21 on Skype, merging.  Will see what Jenkins says before looking at flagging -rc1 version and tagging.

**Comment by dexX7** [comment]
Updates to your branch are added to this PR, so it's fine already.

Green light from my side.

**Pull request merged**
