### PR TITLE
Add cancel reference storage and RPC support

### PR DESCRIPTION
**Pull request by zathras-crypto**

### CODE REVIEW

**Comment by ghost** [comment]
Clean, commented code with descriptive commit messages? DogeW0W

But really, I can't think of what I would pick at :P, nice work!

**Comment by m21** [comment]
fprintf(mp_fp.... will not work any more Zathras, as of few commits back, can you pull and rebuild locally first please, to make sure everything works on your end.

**Comment by zathras-crypto** [comment]
Updated with new logging and checked a couple test txs - still looks good as far as a quick check goes :)

**Comment by achamely** [comment]
Running a test build against this now and evaluating

**Comment by achamely** [comment]
Built cleanly and running omniengine against it now. So far looking good

**Comment by achamely** [comment]
@zathras-crypto 
Bug report:  
"matches": [
      {
        "address":   <-- is returning the address of the sender of order we are in. Not the sender of the matched order.  

ex.  gettrade 37502eb5ddb7779d14844560649d78f1aa11d3c0cded3d7408204dee84e3acc4
trade sent by "mfaiZGBkY4mBqt3PHPD2qWgbaafGa7vR64"
has 1 match ,  "txid": "fbeeee3116cc98def24b066a96bce98b694f4538a5d0bb6e10e7640131f26899"
which was an order sent by "mxaYwMv2Brbs7CW9r5aYuEr1jKTSDXg1TH".   gettrade for 37502 reports the match as being sent by ""mxaYwMv2Brbs7CW9r5aYuEr1jKTSDXg1TH""

**Comment by achamely** [comment]
@zathras-crypto  
Property id returned in a canceled trade is way out of bounds

gettrade_MP 226e5ee92bcb31aae68cf8916c50e7d1ea069db8e0da1396006553ebcb6bbfe3
{...
    "action": "cancel price",
    "cancelledtransactions": [
      {
        "amountunreserved": "1.00000000",
        "propertyid": 18446744071562067971,
        "txid": "18f050ae0df2f4ae8e8b88a0383b183a49f61de48d54e70ed99c557914e1f8ec"

**Pull request merged**
