### PR TITLE
Persistence

### PR DESCRIPTION
**Pull request by wanderingbort**

### CODE REVIEW

**Comment by wanderingbort** [comment]
I would really like to optimize the loading of the most relevant state.  Right now it walks backwards on the active chain, which is great if you have state files (because it usually finds the right one fast).  However, in the case that you have no (valid) state files, it will walk all the way back to the genesis block before determining that you don't have state to load.

I thought I'd put this up though so it can be seen/tested then optimize that one method later.  It may be a better idea to get a list of potential persisted blocks, sort them by height and walk that list instead of the chain.

**Comment by wanderingbort** [comment]
ok fixed the two bugs I found in extended testing.  One is cosmetic the other was certainly not.

**Comment by dexX7** [comment]
Hey, I'm getting this build error, might be based on my setup (VM + Gitian build route on Debian):

```
mastercore.cpp: In function ‘int load_most_relevant_state()’:
mastercore.cpp:1875:155: error: conversion from ‘const value_type* {aka const wchar_t*}’ to non-scalar type ‘const string {aka const std::basic_string<char>}’ requested
mastercore.cpp: In function ‘int write_state_file(const CBlockIndex*, int)’:
mastercore.cpp:1973:32: error: no matching function for call to ‘std::basic_ofstream<char>::open(const value_type*)’
mastercore.cpp:1973:32: note: candidate is:
/usr/include/c++/4.6/fstream:702:7: note: void std::basic_ofstream<_CharT, _Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char, _Traits = std::char_traits<char>, std::ios_base::openmode = std::_Ios_Openmode]
/usr/include/c++/4.6/fstream:702:7: note:   no known conversion for argument 1 from ‘const value_type* {aka const wchar_t*}’ to ‘const char*’
```

Edit: ... this solved it:

```
const string filename = (MPPersistencePath / (boost::format("%s-%s.dat") % statePrefix[i] % curTip->GetBlockHash().ToString()).str().c_str()).c_str();
to
const string filename = (MPPersistencePath / (boost::format("%s-%s.dat") % statePrefix[i] % curTip->GetBlockHash().ToString()).str().c_str()).string();

file.open(balancePath.c_str());
to
file.open(balancePath.string().c_str());
```

Edit: ... on mainnet about 600k new lines are added to debug.log, two for every block, I assume. ("Loading ...balances-x.dat ...", "msc_file_load(): file not found, ...")

**Comment by wanderingbort** [comment]
I can make that change part of the PR, out of curiosity what version of Boost are you using and what compiler?  boost::filesystem::path::c_str() should be a short cut for what you wrote but its possible that boost has a problem or another compiler solution has its templates twisted.  

edit: actually it looks like it may be an issue with wide character support

**Comment by dexX7** [comment]
MinGW + Boost 1.55, or actually: I followed the Gitian build route for Windows with the files provided with the current Bitcoin Core:

https://github.com/bitcoin/bitcoin/blob/master/contrib/gitian-descriptors/
https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#perform-gitian-builds

Faiz didn't experience those errors.

**Comment by ghost** [comment]
behavior looks good, only issue i saw is block files can become corrupt/tampered by renaming the state of a prior block to a more recent one, or renamed; technically you would want to add a SHA hash of the filename too, but overall LGTM

**Comment by ghost** [comment]
note: i was not able to verify consensus due to the pending refactor, as a behavior check this did the following:

loaded state from stored files in ~/.bitcoin/MP_persist/
healing when removal or modification of state
fallback when state is tampered

**Comment by wanderingbort** [comment]
the refactor has made this PR largely untenable.  I'm closing it and I will try to get a new one ready for the refactored structure.

**Pull request closed without merging**
