### PR TITLE
Add update

### PR DESCRIPTION
**Pull request by ghost**
adds persistence to CMPSPInfo and an almost-finshed RPC call

### CODE REVIEW

**Comment by ghost** [comment]
Internal functionality works, external functionality almost works

**Comment by m21** [comment]
Can you add meaningful comments please?
In the context of Master Protocol - what are we doing?
"database" is a very generic name, perhaps in classes it is declared or used explain what is being saved into it please. What it's used for, etc.
What is expected in these locations: at(0), at(1), at(2) ?
I also worry about the amount of data that will be contained in these "database" members. What's the upper bound? Any leveldb limitations? Any JSON limitations?
Leave clues while it's all fresh, will be hard to understand and troubleshoot otherwise, even for the person who wrote it.

**Comment by ghost** [comment]
further improvements from Bart

```
5:20 AM] Bart Wyatt: lexical cast should already be included, if not then please move it to the top of the file with the rest of the includes.  includes in a function body are fun and dangerous
[9:16:28 AM] Bart Wyatt: off hand deserialization looks good.  There is one meta-issue with your form of de/serialization
[9:16:50 AM] Bart Wyatt: that is that the object itself will be in JSON with a single entry that is a string encoded map.
[9:17:23 AM] Bart Wyatt: its purely aesthetic, but for consistency we may want to eventually switch to a JSON object + Array
[9:18:18 AM] Bart Wyatt: you can remove the dupe check in updateSP as well (lines 699-706) as an update will certainly be writing to an existing entry (at least we hope)
```

**Comment by ghost** [comment]
[12:40:04 PM] zathrasc: @Faiz, the it->first, are you storing txid as a string rather than uint256?

clean this up

**Comment by ghost** [comment]
This will come from Zathras now

**Pull request closed without merging**
