### PR TITLE
Change missedtokens rpc name

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Perhaps better left for inclusion in 0.0.9

**Comment by achamely** [comment]
@faizkhan00 I'm going to request this be reopened and added into 0.0.8 as well for consistency.  Keeping the name / field description the same for an existing feature in two branches would be greatly appreciated from an integrators point of view, especially since the functionality is not different.

**Comment by ghost** [comment]
@m21 up to you

**Comment by achamely** [comment]
@m21 can we please have this merged in. It was merged to 0.0.9 and is a simple name change for a field

**Comment by dexX7** [comment]
This is sort of chaotic. ;) How many 0.0.8 versions are there now? 3... 4? Once a release was released I actually assumed it's immutable and any patch/upgrade comes with a version bump - a minor one for compatible patches and a major one for incompatible changes (such as a different RPC label).

**Pull request merged**
