### PR TITLE
Add ecosystem check

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Funds check incoming still, I think it should maybe in be INTERNAL_1packet instead of trade_MP, perhaps... (?)

**Comment by m21** [comment]
Please see the check in int CMPTransaction::logicMath_MetaDEx(), like so:
     // ensure no cross-over of currencies from Test Eco to normal
      if (isTestEcosystemProperty(currency) != isTestEcosystemProperty(desired_currency)) return (PKT_ERROR_METADEX -4);

**Comment by m21** [comment]
Your code should work, but shouldn't this simpler kind of check also work?

if (isTestEcosystemProperty(currency) != isTestEcosystemProperty(desired_currency)) throw "ERROR"...

:)

**Comment by dexX7** [comment]
Speaking of optimization, a side note @m21: `bool isTestEco(unsigned int propID)`: depending on the architecture `unsigned int` might not yield a 64 bit wide integer and you may use `(u)intN_t`, `(u)int_leastN_t` or `(u)int_fastN_t` instead:

> ... types are defined in <inttypes.h> header (cinttypes header in C++) and also are available at <stdint.h> header (cstdint header in C++). The types can be grouped into the following categories:
> 
> Exact-width integer types which are guaranteed to have the same number N of bits across all implementations. Included only if it is available in the implementation.
> 
> Least-width integer types which are guaranteed to be the smallest type available in the implementation, that has at least specified number N of bits. Guaranteed to be specified for at least N=8,16,32,64.
> 
> Fastest integer types which are guaranteed to be the fastest integer type available in the implementation, that has at least specified number N of bits. Guaranteed to be specified for at least N=8,16,32,64.

http://en.wikipedia.org/wiki/C_data_types#Fixed-width_integer_types

I mention this, because zathras once said the 32 bit build is totally broken. :)

**Comment by m21** [comment]
"unsigned int" should never be 64bit, sorry did you say it is possible it is?
The 32bit (Linux) build has issues but not related to datatype sizes directly AFAICT - but debug formatting.

**Comment by dexX7** [comment]
My bad, you are right, the currency identifier should be 32 bit unsigned and I mixed everything.

But to quote further:

> The actual size of integer types varies by implementation. The standard only requires size relations between the data types and minimum sizes for each data type:
> 
> The relation requirements are that the long long is not smaller than long, which is not smaller than int, which is not smaller than short. As char's size is always the minimum supported data type, all other data types can't be smaller.
> 
> The minimum size for char is 8 bits, the minimum size for short and int is 16 bits, for long it is 32 bits and long long must contain at least 64 bits.

This was recently pushed to bitcoin:master and I sort of like the idea of encapsulating values, because it pretty much rules out any ambiguously or inconsistency:

``` c++
typedef int64_t CAmount;
```

https://github.com/bitcoin/bitcoin/blob/master/src/amount.h

**Pull request merged**
