### PR TITLE
UI Merge

### PR DESCRIPTION
**Pull request by zathras-crypto**

### CODE REVIEW

**Comment by dexX7** [comment]
I tested parts of this yesterday via Gitian without compiling errors, however my build did not include all commits and resulted in an APPCRASH. Zathras binary seemed to work -- clean build ongoing (on a very slow notebook) and I'll report back, once results are in.

**Comment by zathras-crypto** [comment]
Thanks DexX.  Note build is only tested without crashes on Ubuntu x64 at mo.
Numerous windows issues - enabling logging will result in appcrash, SP creation transactions will result in appcrash intermittently.

**Comment by dexX7** [comment]
Ah okay, well, ping me, if it's ready for review.

**Comment by zathras-crypto** [comment]
Sure will do mate, thanks.  If you have a chance to build on Linux (note x64 only, x86 builds are definitely broken on all OS's) please feedback, always interested in your thoughts mate.  

Trying to dig into the windows issues but lengthy process!

**Pull request merged**
