### PR TITLE
Tempfix

### PR DESCRIPTION
**Pull request by ghost**
Limits send_MP and sendtoowners_MP to known possible amount without loss of precision

see http://pastie.org/private/difwppuu3d7rvtzpmrhoa

This is because rpcclient.cpp and json-spirit don't support long doubles.

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Nice mate - simple approach to handling the issue until we get more time to
assess :)

**Comment by dexX7** [comment]
Should this be adopted by the spec? Looks like a great source of consensus issues (I know - Core rules, but anyway..).

**Comment by ghost** [comment]
It does create a lot of extra work to support the really high numbers, I for one would breathe a sigh of relief if we _didnt_ need to support higher than 100M.

**Comment by zathras-crypto** [comment]
Hey Dexx,

This is a Core only restriction and just on sends - Core decodes larger txs
just fine.

The issue is the json spirit library handling of floating point precision
when sending bignums over RPC - rather than risk being out by a few
satoshis on the amount we send vs the amount that was in the parameter,
we're just restricting the amount to numbers we know are safe precision
wise until we have more time to address it properly.

Thanks
Z

**Comment by dexX7** [comment]
Aaah gotcha, so this is not a new "protocol rule" enforced only by Core, but an "UI limitation", so to speak. Thanks for the clarification.

**Comment by zathras-crypto** [comment]
Exactly mate, applies solely to outbound txs from Core where we may
potentially encode a value in the packet that is slightly different to the
value supplied in the RPC param in very big number scenarios.

Faiz is right on the money about this being a difficult issue coding wise
(hopefully we get some success modifying json spirit), though a restriction
to 100M tokens within the protocol I think would be too drastic at this
early stage :) just IMO.

Thanks
Z

**Comment by dexX7** [comment]
Wouldn't it be possible to bypass the restrictions by feeding the data as string and not as number, followed by an internal validation and cast? Not very elegant though. This is/was also a known issue in Bitcoin Core by the way: https://github.com/bitcoin/bitcoin/pull/3127

While quickly looking over the code, it's actually interesting to see that there are a few places where additional limitations are enforced - so far nothing that affects MCore, but for example [AmountFromValue](https://github.com/faizkhan00/mastercore/blob/michael/src/rpcserver.cpp#L83) limits the range to `dAmount <= 0.0 || dAmount > 21000000.0`.. :)

**Comment by zathras-crypto** [comment]
Completely correct - pulling in as string is the way we've discussed
getting around it - I'm initially anti that because it means telling
integrators to adapt their RPC calls to send numbers in as strings which
seems ugly, but perhaps that's not as big a deal as I think it might be...

Z

**Pull request merged**
