### PR TITLE
Extract, move and test StrToInt64

### PR DESCRIPTION
**Pull request by dexX7**
This basically breaks down #173.
- Rename strtToInt64 to StrToInt64
- Moved into new files /mastercore/parse_string.h and /mastercore/parse_string.cpp
- Adopted and converted @zathras-crypto's tests to BOOST tests which can be run via ./src/test/test_bitcoin
- Namespace "mastercore" is used
- I tend to let this sit in it's own file, because it's only used in mastercore_rpc and sendmpdialog whereby Format__MP is used in other places

Build and practical tests done.

### CODE REVIEW

**Comment by m21** [comment]
@zathras-crypto comments please?
I am kinda against creating a subdirectory for mastercore at this time Dexx:
1 = makes #including harder for QT 
2 = we only have a handful of files
3 = 1 more reason I can't yet discuss

**Comment by dexX7** [comment]
I see. Are you fine with "mastercore_strtoint64.h" and "mastercore_strtoint64.cpp"? The only other functions at the moment that may qualify for a combined file are the Format_MP and rounduint64, but all three have very different dependencies and scopes (at least in practise), so I tend to single purpose files. What do you think?

I'm curious now.. :p mind to send me an email to dexx@bitwatch.co re: 3? ;)

**Comment by m21** [comment]
Heh sorry.
Maybe: mastercore_util or mastercore_strutil?

**Comment by dexX7** [comment]
Rebased, for now it's still in mastercore_parse_string. Hmm.. util is sort of generic and doesn't tell much.

**Pull request merged**
